#!groovy

// Generated by IBM TransformationAdvisor
// Wed Jan 30 14:22:26 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}